inherit_from: rubocop.yml

AllCops:
  SuggestExtensions: false

# Development dependencies intentionally declared in gemspec per gem best practices
Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "bin/ci"

Rails/Output:
  Exclude:
    - "lib/rails_quality_assurance/ci.rb"

Rails/Exit:
  Exclude:
    - "lib/rails_quality_assurance/ci.rb"
