#!/bin/sh
# Generated by rails_quality_assurance. Delegates to the tracked project hook.
# Keep this file; shared hook managers may replace it with a symlink that
# forwards here too.
exec "$(git rev-parse --show-toplevel)/.githooks/pre-commit" "$@"
